name: NiftyMonitor
on:
  schedule:
    - cron: '*/15 3-10 * * 1-5' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python collector.py
      - name: Commit and Push
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add data.json history.json
          git commit -m "Update Nifty Data" || exit 0
          git push
